In [1]:
import pandas as pd 
df=pd.read_csv('automobile_data.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

# MISSING VALUE

In [3]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [4]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='number':
            df[col].fillna(df[col].mean(),inplace=True)
        else:
            df[col].fillna(df[col].mode()[0],inplace=True)

C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_1944\3412393898.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             61 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

# ENCODING

In [7]:
from sklearn.preprocessing import LabelEncoder
encodlash=LabelEncoder()

In [8]:
for col in df.columns:
    if df[col].dtype=='object':
        df[col]=encodlash.fit_transform(df[col])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     int64
 2   body-style        61 non-null     int64
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     int64
 6   num-of-cylinders  61 non-null     int64
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             61 non-null     float64
dtypes: float64(3), int64(7)
memory usage: 4.9 KB

# Scaling  jarayonini boshlaymiz

In [11]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaling_step=StandardScaler()

# raqamli ustunlarni aniqlaymiz  // target qiymatni tushurib yuboramiz

In [12]:
num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('price')

In [13]:
num_col

Index(['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type',
       'num-of-cylinders', 'horsepower', 'average-mileage'],
      dtype='object')

In [15]:
df[num_col]=scaling_step.fit_transform(df[num_col])

# input va output qiymatlarni belgilab olamiz

In [21]:
x=df.drop('price',axis=1)

In [24]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     float64
 1   company           61 non-null     float64
 2   body-style        61 non-null     float64
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     float64
 6   num-of-cylinders  61 non-null     float64
 7   horsepower        61 non-null     float64
 8   average-mileage   61 non-null     float64
dtypes: float64(9)
memory usage: 4.4 KB

# bizda price ustuni target qiymat

In [25]:
y=df['price']

In [26]:
from sklearn.model_selection import train_test_split

# Data setni Train Test Validation qismlariga ajratib olamiz

In [27]:
x_train,x_temp,y_train,y_temp=train_test_split(x,y,test_size=0.2,random_state=42)
x_val,x_test,y_val,y_test=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42)

In [28]:
x_train

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage
3,-1.502166,-1.468280,0.333899,0.198971,0.251800,0.042718,-0.154440,-0.110249,-0.223651
53,1.194063,1.153137,1.405891,-0.419966,-0.244373,0.042718,-0.154440,-0.863774,0.148423
17,-0.828109,-0.812926,-0.738093,-0.721887,-1.136047,0.042718,-0.154440,-0.750745,0.644522
8,-1.224613,-1.249829,0.333899,0.410315,0.266182,0.042718,-0.154440,-0.129087,-0.347676
6,-1.383215,-1.468280,1.405891,1.104732,1.409537,0.042718,-1.201197,0.040456,-0.843775
41,0.520006,0.716234,0.333899,-0.601119,-0.560773,0.042718,-0.154440,-0.731907,0.644522
4,-1.462516,-1.468280,0.333899,0.138586,0.251800,0.042718,-1.201197,0.134646,-0.967800
44,0.638957,0.716234,0.333899,0.289547,0.827073,1.779912,0.892318,0.831657,-0.843775
19,-0.510906,-0.594474,0.333899,-0.299198,0.165509,0.042718,-0.154440,-0.129087,-0.223651
47,0.876860,0.934686,-0.738093,-0.012374,0.187082,-1.694476,-2.247954,3.393641,-1.091824
52,1.154413,1.153137,1.405891,-0.419966,-0.244373,0.042718,-0.154440,-0.863774,0.148423
25,-0.273003,-0.157572,0.333899,2.191646,1.905710,-2.563073,0.892318,1.283771,-1.339874
57,1.630218,1.371589,0.333899,-0.178430,-0.100555,0.042718,-0.154440,-1.052155,1.388670
15,-0.907410,-1.031377,0.333899,-0.601119,-1.028183,0.042718,-0.154440,-0.713069,1.512695
58,1.788820,1.371589,0.333899,-0.178430,-0.100555,0.042718,-0.154440,-0.147926,0.024398
27,-0.193702,0.060880,-0.738093,-0.812463,-1.006610,0.042718,-0.154440,-0.750745,0.520497
9,-1.184963,-1.249829,0.333899,0.410315,0.266182,0.042718,0.892318,0.247675,-0.595725
30,-0.074751,0.060880,-0.738093,-0.480351,-0.294710,2.648509,4.032590,-0.129087,-1.091824
36,0.321754,0.497783,-0.738093,-0.721887,-1.136047,0.042718,-0.154440,-0.750745,1.388670
26,-0.233353,-0.157572,0.333899,0.531083,1.337628,1.779912,2.985832,2.903849,-1.587923
24,-0.312653,-0.157572,0.333899,2.191646,1.905710,-2.563073,0.892318,1.283771,-1.339874
43,0.599307,0.716234,1.405891,-0.601119,-0.208419,0.042718,-0.154440,-0.731907,0.644522
11,-1.066012,-1.249829,0.333899,0.757524,1.488637,0.042718,0.892318,1.396800,-1.215849
32,0.123501,0.279331,0.333899,1.738765,1.280101,0.042718,-1.201197,0.285351,-0.471701
54,1.511267,1.153137,1.405891,0.908484,1.057182,-2.563073,0.892318,0.907009,-0.843775
56,1.590567,1.371589,0.333899,-0.178430,-0.100555,0.042718,-0.154440,-0.430497,0.148423
37,0.361404,0.497783,-0.738093,-0.721887,-1.136047,0.042718,-0.154440,-0.750745,0.644522
29,-0.114401,0.060880,-0.738093,-0.812463,-1.006610,0.042718,-0.154440,-0.750745,0.644522
45,0.797559,0.934686,-1.810084,-1.355920,-0.301901,0.911315,0.892318,1.867753,-1.091824
1,-1.581467,-1.686732,-2.882076,-1.491784,-0.309091,-2.563073,-0.154440,0.059294,-0.595725
21,-0.431605,-0.376023,0.333899,-0.631311,-0.172464,0.042718,-0.154440,-0.562364,-0.223651
2,-1.541817,-1.686732,-0.738093,-0.601119,-0.136509,1.779912,0.892318,0.869333,-0.843775
48,0.995811,1.153137,-0.738093,-0.419966,-1.035374,0.042718,-0.154440,-0.863774,1.140621
39,0.440705,0.497783,0.333899,-0.329390,-0.050219,0.042718,-0.154440,-0.373983,-0.099626
35,0.242453,0.279331,-1.810084,2.040686,1.876946,1.779912,-2.247954,1.434476,-1.463899
23,-0.352304,-0.376023,0.333899,-0.601119,-1.236719,0.042718,-0.154440,-0.713069,1.512695
50,1.075112,1.153137,-0.738093,-0.419966,-1.035374,0.042718,-0.154440,-0.863774,0.644522
10,-1.105662,-1.249829,0.333899,0.757524,1.143473,0.042718,0.892318,1.396800,-1.215849
22,-0.391954,-0.376023,0.333899,-0.601119,-1.236719,0.042718,-0.154440,-0.713069,1.512695
18,-0.550556,-0.594474,1.405891,-0.299198,-1.150428,0.042718,-0.154440,-0.600040,0.520497
60,1.868120,1.590040,1.405891,0.878292,1.129091,0.042718,-0.154440,0.115808,-0.347676
20,-0.471255,-0.594474,0.333899,-0.299198,-0.287519,0.042718,-0.154440,-0.147926,-0.099626
7,-1.264264,-1.249829,0.333899,0.410315,0.266182,0.042718,-0.154440,-0.129087,-0.347676
42,0.559656,0.716234,0.333899,-0.601119,-0.560773,0.042718,-0.154440,-0.731907,0.644522
14,-0.947060,-1.031377,-0.738093,-0.601119,-1.236719,0.042718,-0.154440,-0.713069,1.512695
28,-0.154052,0.060880,-0.738093,-0.812463,-1.006610,0.042718,-0.154440,-0.750745,0.644522
51,1.114762,1.153137,1.405891,-0.419966,-0.244373,0.042718,-0.154440,-0.863774,0.644522
38,0.401054,0.497783,0.333899,-0.329390,-0.050219,0.042718,-0.154440,-0.373983,-0.099626

# Model tanlab olamiz bizda [Decision Tree Classifier] modeli tanlandi

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [30]:
model=DecisionTreeClassifier()

In [31]:
model

DecisionTreeClassifier()

# Train qilish jarayoni

In [32]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
y_pred=model.predict(x_test)

In [34]:
y_pred

array([13415.,  7995., 16500., 41315.,  7995., 34028., 17450.])

In [35]:
len(y_pred)

7

In [36]:
len(x_test)

7

In [37]:
x_test

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage
59,1.828470,1.590040,0.333899,0.878292,1.129091,0.042718,-0.154440,0.115808,-0.347676
40,0.480355,0.716234,0.333899,-0.601119,-0.560773,0.042718,-0.154440,-0.995641,2.380868
0,-1.621118,-1.686732,-2.882076,-1.491784,-0.309091,-2.563073,-0.154440,0.059294,-0.595725
12,-1.026361,-1.249829,0.333899,1.738765,1.718746,0.042718,0.892318,1.396800,-1.339874
55,1.550917,1.371589,0.333899,-0.178430,-0.100555,0.042718,-0.154440,-1.052155,1.388670
46,0.837209,0.934686,-2.882076,-1.355920,-0.301901,0.911315,0.892318,1.867753,-1.091824
5,-1.422866,-1.468280,0.333899,0.198971,0.302136,0.042718,-1.201197,0.040456,-0.843775

# Accuracy jarayoni

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
score=accuracy_score(y_test,y_pred)

In [40]:
score

0.0