In [3]:
import pandas as pd

# DATASETNI YUKLAB OLAMIZ

In [5]:
df = pd.read_csv("personality_dataset.csv")

In [11]:
df.head()

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,col_No,col_Yes,col_No,col_Yes,col_Extrovert,col_Introvert
0,4.0,4.0,6.0,13.0,5.0,1,0,1,0,1,0
1,9.0,0.0,0.0,0.0,3.0,0,1,0,1,0,1
2,9.0,1.0,2.0,5.0,2.0,0,1,0,1,0,1
3,0.0,6.0,7.0,14.0,8.0,1,0,1,0,1,0
4,3.0,9.0,4.0,8.0,5.0,1,0,1,0,1,0

# TUSHIRIB QOLDIRILGAN QIYMATLARNI TO`LDIRAMIZ

In [7]:
for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)

C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_9816\2286963672.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_9816\2286963672.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   object
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   object
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   object
dtypes: float64(5), object(3)
memory usage: 181.4+ KB

# ENCODING QILAMIZ .. ONE-HOT VA LABEL ENCODINGDAN FOYDALANAMIZ

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=6:
            dummies=pd.get_dummies(df[col],prefix='col', dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)

        else:
            df[col]=encoder.fit_transform(df[col])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time_spent_Alone         2900 non-null   float64
 1   Social_event_attendance  2900 non-null   float64
 2   Going_outside            2900 non-null   float64
 3   Friends_circle_size      2900 non-null   float64
 4   Post_frequency           2900 non-null   float64
 5   col_No                   2900 non-null   int64
 6   col_Yes                  2900 non-null   int64
 7   col_No                   2900 non-null   int64
 8   col_Yes                  2900 non-null   int64
 9   col_Extrovert            2900 non-null   int64
 10  col_Introvert            2900 non-null   int64
dtypes: float64(5), int64(6)
memory usage: 249.3 KB

# RAQAMLI USTUNLARNI ALOHIDA QILIB OLAMIZ TARGET USTUNINI TASHLAB YUBORAMIZ

In [ ]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('col_Extrovert')
num_col

Index(['Time_spent_Alone', 'Social_event_attendance', 'Going_outside',
       'Friends_circle_size', 'Post_frequency', 'col_No', 'col_Yes', 'col_No',
       'col_Yes', 'col_Introvert'],
      dtype='object')

# STANDART SCALING ORQALI SCALING QILAMIZ

In [17]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler,RobustScaler
scaler_standart=StandardScaler()

df[num_col]=scaler_standart.fit_transform(df[num_col])

In [18]:
df.head()

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,col_No,col_Yes,col_No,col_Yes,col_Extrovert,col_Introvert
0,-0.147014,0.012759,1.350613,1.590680,0.496104,0.972784,-0.972784,0.970772,-0.970772,1,-0.972113
1,1.306226,-1.379944,-1.350613,-1.481437,-0.195199,-1.027977,1.027977,-1.030108,1.030108,0,1.028687
2,1.306226,-1.031768,-0.450204,-0.299853,-0.540850,-1.027977,1.027977,-1.030108,1.030108,0,1.028687
3,-1.309607,0.709111,1.800817,1.826996,1.533059,0.972784,-0.972784,0.970772,-0.970772,1,-0.972113
4,-0.437663,1.753638,0.450204,0.409096,0.496104,0.972784,-0.972784,0.970772,-0.970772,1,-0.972113

# TARGET USTUNINI TASHLAB YUBORAMIZ

In [19]:
x=df.drop('col_Extrovert',axis=1)
x.info()
y=df['col_Extrovert'] 
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time_spent_Alone         2900 non-null   float64
 1   Social_event_attendance  2900 non-null   float64
 2   Going_outside            2900 non-null   float64
 3   Friends_circle_size      2900 non-null   float64
 4   Post_frequency           2900 non-null   float64
 5   col_No                   2900 non-null   float64
 6   col_Yes                  2900 non-null   float64
 7   col_No                   2900 non-null   float64
 8   col_Yes                  2900 non-null   float64
 9   col_Introvert            2900 non-null   float64
dtypes: float64(10)
memory usage: 226.7 KB
<class 'pandas.core.series.Series'>
RangeIndex: 2900 entries, 0 to 2899
Series name: col_Extrovert
Non-Null Count  Dtype
--------------  -----
2900 non-null   int64
dtypes: int64(1)
memory usage: 22.8 KB

In [21]:
from sklearn.model_selection import train_test_split

# DATASETNI KERAKLI QISMLARGA BO`LIB CHIQAMIZ

In [22]:
x_train,x_temp,y_train,y_temp=train_test_split(x,y,test_size=0.2,random_state=42)
x_val,x_test,y_val,y_test=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# TRAIN QILAMIZ

In [26]:
ligistic_model = LogisticRegression()
ligistic_model

LogisticRegression()

In [27]:
ligistic_model.fit(x_train, y_train)

LogisticRegression()

# PREDICT QILIB KO`RAMIZ

In [29]:
linear_pred=ligistic_model.predict(x_test)
linear_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0])

In [30]:
from sklearn.metrics import accuracy_score

# QANCHALIK TOGRI ISHLASHINI TEKSHIRIB KO`RAMIZ

In [31]:
linear_score=accuracy_score(y_test,linear_pred)
linear_score

1.0

# BOSHQA MODEL ORQALI HAM TEKSHIRIB KO`RAMIZ

In [34]:
Random_forest_model = RandomForestClassifier()
Random_forest_model

RandomForestClassifier()

In [35]:
Random_forest_model.fit(x_train, y_train)

RandomForestClassifier()

In [38]:
random_pred=Random_forest_model.predict(x_test)
random_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0])

In [40]:
random_score=accuracy_score(y_test,random_pred)
random_score

1.0